BTDSTD_DIR_PATH = "C:/GameDev//BTDSTD"
BTDSTD_INCLUDE_DIR_PATH = "C:/GameDev//BTDSTD/includes"
BTDSTD_DEP_DIR_PATH = "C:/GameDev//BTDSTD-Deps"
GLFW_DIR_PATH = "C:/GameDev//BTDSTD-Deps/glfw"
GLM_DIR_PATH = "C:/GameDev//BTDSTD-Deps/glm"
YAML_CPP_DIR_PATH = "C:/GameDev//BTDSTD-Deps/yaml-cpp"
ASSIMP_DIR_PATH = "C:/GameDev//BTDSTD-Deps/Assimp_DLLs_Libs"
IMGUI_DIR_PATH = "C:/GameDev//BTDSTD-Deps/imgui"
VULKAN_DIR_PATH = "C:/VulkanSDK/1.3.275.0"
include "C:/GameDev//BTDSTD"
